services:
  coursemate_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - coursemate_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --username postgres --dbname postgres --port 5432 --quiet
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 10s
  server:
    build:
      context: ./server/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /coursemate/builder/server
    depends_on:
      coursemate_db:
        condition: service_healthy
      

volumes:
  coursemate_data:
