name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: front
        shell: bash

      - name: Build
        run: npm run build
        working-directory: front
        shell: bash

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: front
        shell: bash

      - name: Run ESLint
        run: npm run lint
        working-directory: front
        shell: bash

  type-check-frontend:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Install Node Packages
        run: npm ci
        working-directory: front
        shell: bash

      - name: Type Check
        run: npx tsc --noEmit
        working-directory: front
        shell: bash
